"""Reason codes. Every denial is machine-readable, stable, and greppable.

Codes are frozen public API: the trace console, the red-team runner and the
agent's own error handling all switch on them. Add new codes; never renumber.
"""
from __future__ import annotations

from enum import StrEnum


class Reason(StrEnum):
    OK = "OK"

    # G1 schema
    SCHEMA_INVALID = "G1_SCHEMA_INVALID"
    SCHEMA_UNKNOWN_FIELD = "G1_SCHEMA_UNKNOWN_FIELD"
    SCHEMA_BAD_AMOUNT = "G1_SCHEMA_BAD_AMOUNT"
    SCHEMA_CURRENCY = "G1_SCHEMA_CURRENCY_UNSUPPORTED"
    SCHEMA_ACTION_UNSUPPORTED = "G1_SCHEMA_ACTION_UNSUPPORTED"

    # G2 signature / authority
    SIG_UNKNOWN_KEY = "G2_SIG_UNKNOWN_KEY"
    SIG_BAD_ALG = "G2_SIG_BAD_ALG"
    SIG_INVALID = "G2_SIG_INVALID"
    SIG_SUBJECT_MISMATCH = "G2_SIG_SUBJECT_MISMATCH"
    SIG_AGENT_NOT_DELEGATED = "G2_SIG_AGENT_NOT_DELEGATED"
    SIG_MERCHANT_KEY_MISMATCH = "G2_SIG_MERCHANT_KEY_MISMATCH"
    SIG_CART_NOT_BOUND_TO_INTENT = "G2_SIG_CART_NOT_BOUND_TO_INTENT"

    # G3 freshness / replay
    FRESH_INTENT_EXPIRED = "G3_FRESH_INTENT_EXPIRED"
    FRESH_QUOTE_EXPIRED = "G3_FRESH_QUOTE_EXPIRED"
    FRESH_ISSUED_IN_FUTURE = "G3_FRESH_ISSUED_IN_FUTURE"
    FRESH_NONCE_REPLAY = "G3_FRESH_NONCE_REPLAY"
    FRESH_MANDATE_REVOKED = "G3_FRESH_MANDATE_REVOKED"

    # G4 budget
    BUDGET_PER_TXN_EXCEEDED = "G4_BUDGET_PER_TXN_EXCEEDED"
    BUDGET_TOTAL_EXCEEDED = "G4_BUDGET_TOTAL_EXCEEDED"
    BUDGET_CURRENCY_MISMATCH = "G4_BUDGET_CURRENCY_MISMATCH"
    BUDGET_ZERO_AMOUNT = "G4_BUDGET_ZERO_AMOUNT"

    # G5 allowlist
    ALLOW_MERCHANT = "G5_ALLOW_MERCHANT_NOT_PERMITTED"
    ALLOW_PAYEE = "G5_ALLOW_PAYEE_NOT_PERMITTED"
    ALLOW_SKU = "G5_ALLOW_SKU_NOT_PERMITTED"
    ALLOW_CATEGORY = "G5_ALLOW_CATEGORY_NOT_PERMITTED"
    ALLOW_DENYLIST_HIT = "G5_ALLOW_DENYLIST_HIT"

    # G6 price binding
    PRICE_LINE_MATH = "G6_PRICE_LINE_MATH_MISMATCH"
    PRICE_CART_TOTAL = "G6_PRICE_CART_TOTAL_MISMATCH"
    PRICE_ACTION_AMOUNT = "G6_PRICE_ACTION_AMOUNT_MISMATCH"
    PRICE_CART_HASH = "G6_PRICE_CART_HASH_MISMATCH"
    PRICE_QUANTITY_INVALID = "G6_PRICE_QUANTITY_INVALID"
    PRICE_REFUND_EXCEEDS_SETTLED = "G6_PRICE_REFUND_EXCEEDS_SETTLED"
    PRICE_NO_SETTLED_PAYMENT = "G6_PRICE_NO_SETTLED_PAYMENT"
    PRICE_CAPTURE_EXCEEDS_AUTHORISED = "G6_PRICE_CAPTURE_EXCEEDS_AUTHORISED"

    # G7 velocity / breaker
    VEL_TXN_COUNT = "G7_VEL_TXN_COUNT_EXCEEDED"
    VEL_RATE_LIMIT = "G7_VEL_RATE_LIMIT_EXCEEDED"
    VEL_BREAKER_OPEN = "G7_VEL_BREAKER_OPEN"
    VEL_KILL_SWITCH = "G7_VEL_KILL_SWITCH_ENGAGED"

    # G8 idempotency
    IDEM_IN_FLIGHT = "G8_IDEM_IN_FLIGHT"
    IDEM_REPLAYED = "G8_IDEM_REPLAYED_RESULT"

    # execution layer (not a gate — post-authorisation)
    EXEC_PROVIDER_ERROR = "X_EXEC_PROVIDER_ERROR"
    EXEC_STOP_RULE = "X_EXEC_STOP_RULE_TRIGGERED"
    EXEC_UNKNOWN_STATE = "X_EXEC_UNKNOWN_STATE_RESOLVED"
    EXEC_COMPENSATED = "X_EXEC_COMPENSATED"
    EXEC_CAPABILITY_EXPIRED = "X_EXEC_CAPABILITY_EXPIRED"
    EXEC_CAPABILITY_SPENT = "X_EXEC_CAPABILITY_SPENT"
    EXEC_CAPABILITY_SCOPE = "X_EXEC_CAPABILITY_SCOPE_VIOLATION"


class KernelDenied(Exception):
    """Raised only at the API edge; internally gates return verdicts, not exceptions."""

    def __init__(self, reason: Reason, detail: str = "", gate: str = ""):
        super().__init__(f"{reason}: {detail}")
        self.reason = reason
        self.detail = detail
        self.gate = gate
